version: '3.8'

services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: sis03_security
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/sis03_security?useTimezone=true&amp&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1111
    depends_on:
      - mysql

volumes:
  db_data:
