version: '3.8'

services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: sis03_security
      MYSQL_USER: welton
      MYSQL_PASSWORD: testeabc
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
